### PR TITLE
Convert to a cli script.

### PR DESCRIPTION
**Pull request by ghost**
This PR changes -

- Whole repo to a script, so user can just install the tool with pip and use as a cli tool
- Download will be stored in `currentfolder/book-name` format
- Readded the pick packages as it's still needed by the search module

If you want to test before merge you can run 
```sh
pip install git+https://github.com/rozari0/TokySnatcher.git
tokysnatcher
```

### CODE REVIEW

**Comment by rahaaatul** [comment]
Thank you for the pull request. Also, I'm sorry for being so late, I did not get any notifications for it.

I like the idea of that. And I'm all for it. Did it work as expected for you?

**Comment by ghost** [comment]
> I like the idea of that. And I'm all for it. Did it work as expected for you?

yes, it did. You can try installing by `pip install git+https://github.com/TheCrowClub/TokySnatcher`.

**Comment by rahaaatul** [comment]
It's merged.

Thank you for the contribution, I really appreciate it.

**Comment by rahaaatul** [comment]
Can we upload it to PYPI.org @rozari0 ?

Edit: I've released it. It's now available in pypi.org:

```shell
pip install tokysnatcher
```

**Pull request merged**
